version: "3.8"

services:
  server:
    image: bgoi-server:latest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080

  mysql:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: SLYwX1ptpSVHi17bqhlpoRF4p95kxkuxLh
      MYSQL_DATABASE: data
    healthcheck:
      test: curl --fail 'http://localhost:3306' || exit 1
      interval: 10s
      timeout: 1s
      retries: 5

volumes:
  data:
